### ISSUE TITLE
Failed to run demo

### ISSUE THREAD

**Issue by tuloski** [interledger/five-bells-demo#17]
Stacktrace:

> five-bells-demo@1.1.1 start /home/odroid/five-bells-demo
> rm -f data/*.sqlite ; node index.js

/home/odroid/five-bells-demo/index.js:3
const demo = require('./src/services/demo')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

npm ERR! five-bells-demo@1.1.1 start: `rm -f data/*.sqlite ; node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the five-bells-demo@1.1.1 start script.
npm ERR! This is most likely a problem with the five-bells-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -f data/*.sqlite ; node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls five-bells-demo
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.82-52
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/odroid/five-bells-demo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/odroid/five-bells-demo/npm-debug.log
npm ERR! not ok code 0

**Comment by yxxyun** [comment]
I think you should update nodejs to 4.XX,not 0.10

**Comment by tuloski** [comment]
YEah, that's the problem :)
