### ISSUE TITLE
Installation problem on Mac OS X (npm --> a problem with the five-bells-demo package?)

### ISSUE THREAD

**Issue by romanix** [interledger/five-bells-demo#18]
Installation problem with five-bells demo on Mac OS X 

uname -a
Darwin xxxx.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

After installing bower ... I tried:

10084  sudo npm install --only=prod --no-optional
10085  sudo npm start

/Users/some_username/some_dir/projects/five-bells-demo/src/services/demo.js:3
const Demo = require('../lib/demo').Demo
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/some_username/some_dir/projects/five-bells-demo/index.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! five-bells-demo@1.1.1 start: `rm -f data/*.sqlite ; node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the five-bells-demo@1.1.1 start script.
npm ERR! This is most likely a problem with the five-bells-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -f data/*.sqlite ; node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls five-bells-demo
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/some_username/some_dir/projects/five-bells-demo
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/some_username/some_dir/projects/five-bells-demo/npm-debug.log
npm ERR! not ok code 0

**Comment by tuloski** [comment]
Look at closed issues...you need to install newer nodejs. You're using 0.10.26 but you need 4 or higher....well actually I'm having problems with nodejs 5 too :)

**Comment by justmoon** [comment]
See #17 and [README.md](https://github.com/interledger/five-bells-demo/blob/master/README.md) - you need Node 4.x.x.

Apparently Node 5.0.0 doesn't work yet with some upstream packages (#19), so Node 4.2.1 is recommended for now.
