### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by tuloski** [interledger/five-bells-demo#19]
I installed nodejs 5.0.0 (latest stable).
Trying to run the demos it said: "Errors importing deep-diff ..."
I installed deep-diff from npm and now the following error:

"/home/odroid/five-bells-demo/node_modules/sequelize/lib/sequelize.js:205    throw new Error('The dialect ' + this.getDialect() + ' is not supported. ('+err+')');    ^Error: The dialect sqlite is not supported. (Error: Please install sqlite3 package manually)    at DB.Sequelize (/home/odroid/five-bells-demo/node_modules/sequelize/lib/sequelize.js:205:11)    at DB (/home/odroid/five-bells-demo/node_modules/five-bells-shared/lib/db.js:20:7)    at Object.<anonymous> (/home/odroid/five-bells-demo/node_modules/five-bells-ledger/src/services/db.js:8:18)    at Module._compile (module.js:425:26)    at Object.Module._extensions..js (module.js:432:10)    at Module.load (module.js:356:32)    at Function.Module._load (module.js:311:12)    at Module.require (module.js:366:17)    at require (module.js:385:17)    at Object.<anonymous> (/home/odroid/five-bells-demo/node_modules/five-bells-ledger/src/controllers/transfers.js:7:12)    at Module._compile (module.js:425:26)    at Object.Module._extensions..js (module.js:432:10)    at Module.load (module.js:356:32)    at Function.Module._load (module.js:311:12)    at Module.require (module.js:366:17)    at require (module.js:385:17)npm ERR! Linux 3.10.82-52npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--color"npm ERR! node v5.0.0npm ERR! npm  v3.3.6npm ERR! code ELIFECYCLEnpm ERR! five-bells-ledger@5.0.0 start: `node app.js "--color"`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the five-bells-ledger@5.0.0 start script 'node app.js "--color"'.npm ERR! This is most likely a problem with the five-bells-ledger package,npm ERR! not with npm itself.npm ERR! Tell the author that this fails on your system:npm ERR!     node app.js "--color"npm ERR! You can get their info via:npm ERR!     npm owner ls five-bells-ledgernpm ERR! There is likely additional logging output above.npm ERR! Please include the following file with any support request:npm ERR!     /home/odroid/five-bells-demo/node_modules/five-bells-ledger/npm-de"

Do I need to install sqlite3?

**Comment by emschwartz** [comment]
It does need `sqlite3` but it should have installed that when you run `npm install`

**Comment by emschwartz** [comment]
Hmm, I'm seeing the same issue as well with node v5.

We'll look into that issue (from a first glance it appears to be a problem with Sequelize not working properly with the latest node) but in the meantime I would suggest using v4.2.1.

**Comment by justmoon** [comment]
Hmm, I just tried to reproduce the issue, but it works fine for me using Node.js 5.0.0 on Linux. Did something get fixed upstream or are you still experiencing this problem?

**Comment by tuloski** [comment]
Actually I have the same error even if rolled back to node 4.2.1

PS: running it on odroid (arm architecture), but I don't think the architecture is the problem here.

**Comment by justmoon** [comment]
Please try installing node-sqlite3 manually and running `node -p 'require("sqlite3").VERSION'`. The error you posted means that something is going wrong during installation, so you end up missing that module.

**Comment by justmoon** [comment]
Closed for inactivity. Feel free to reopen if this is still an issue.

**Comment by wealth** [comment]
had same-looking sqlite error, fixed with cd node_modules/five-bells-ledger/ && npm install sqlite3
