### ISSUE TITLE
bower dependency needed

### ISSUE THREAD

**Issue by brettmollin** [interledger/five-bells-demo#21]
On a clean install of OSX Yosemite I had to install bower also.

sudo npm install bower -g

**Comment by jtremback** [comment]
I'm not familiar with Bower, does it require a global install? If so, that's pretty goofy.

**Comment by emschwartz** [comment]
Good catch. Should be solved by https://github.com/interledger/five-bells-visualization/commit/ff224bd52cb2b325c455f94a50b6457ed87b0d3c. If you run `npm update five-bells-visualization` it should work without the global `bower` install
